In [ ]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
import json
!source .env


: 

In [11]:
with open('./data/hidden_layer_activations.json') as f:
    data = json.load(f)

df = pd.DataFrame(data)
# np.array(df.pythia_1b_107000[0]).shape
df.head()

title  \
0                   Miniopterus aelleni   
1                          William Hely   
2                         Alfred Lennon   
3  Suriname at the 2008 Summer Olympics   
4                         Ivor McIntyre   

                                                text  \
0  Miniopterus aelleni is a bat in the genus Mini...   
1  Air Vice Marshal William Lloyd ( Bill ) Hely ,...   
2  Alfred " Alf / Freddie " Lennon ( 14 December ...   
3  Suriname sent a delegation of four people to c...   
4  Ivor Ewing McIntyre , CBE , AFC & Bar ( 6 Octo...   

                                    pythia_1b_107000  \
0  [[0.8097250461578369, -0.08863230049610138, 0....   
1  [[0.29645395278930664, 0.001676870509982109, -...   
2  [[0.24661314487457275, -0.46500205993652344, 0...   
3  [[-0.17580823600292206, 0.15452691912651062, 0...   
4  [[0.44491976499557495, -0.04492417722940445, 0...   

                                    pythia_1b_125000  \
0  [[0.8933351039886475, 0.00031185150146484375, ...   
1  [[0.4378296136856079, -0.056834038347005844, -...   
2  [[0.2184232473373413, -0.3985990285873413, 0.5...   
3  [[-0.1604813039302826, 0.1782083958387375, 0.4...   
4  [[0.3254651725292206, -0.05369982495903969, 0....   

                                    pythia_1b_143000  
0  [[0.8081629872322083, 0.02379695326089859, 0.2...  
1  [[0.4149337708950043, -0.042567234486341476, -...  
2  [[0.33349162340164185, -0.40083709359169006, 0...  
3  [[-0.1370622217655182, 0.11922620236873627, 0....  
4  [[0.392804890871048, -0.07561272382736206, 0.3...

In [12]:
# Compute the current average L2 norm
avg_norm = np.mean([np.linalg.norm(v) for col in df.columns[2:] for v in df[col]])

# Compute the scaling factor
scale = 2048 / avg_norm

# Scale each vector by the scaling factor
for col in df.columns[2:]:
    df[col] = df[col].apply(lambda x: scale * np.array(x))

df.head()

title  \
0                   Miniopterus aelleni   
1                          William Hely   
2                         Alfred Lennon   
3  Suriname at the 2008 Summer Olympics   
4                         Ivor McIntyre   

                                                text  \
0  Miniopterus aelleni is a bat in the genus Mini...   
1  Air Vice Marshal William Lloyd ( Bill ) Hely ,...   
2  Alfred " Alf / Freddie " Lennon ( 14 December ...   
3  Suriname sent a delegation of four people to c...   
4  Ivor Ewing McIntyre , CBE , AFC & Bar ( 6 Octo...   

                                    pythia_1b_107000  \
0  [[27.840908732781635, -3.047458888171076, 6.06...   
1  [[10.193024758518593, 0.05765611308014873, -3....   
2  [[8.479340106047408, -15.988241900973222, 23.3...   
3  [[-6.044843340654906, 5.3131243408771915, 20.2...   
4  [[15.297749068562103, -1.5446353352584277, 13....   

                                    pythia_1b_125000  \
0  [[30.715687029754857, 0.010722441193663208, 3....   
1  [[15.05396723612521, -1.9541340385140646, -2.1...   
2  [[7.510082247167318, -13.705095610581393, 17.4...   
3  [[-5.517854927720572, 6.127368428955065, 15.67...   
4  [[11.190522273061541, -1.846369866839401, 10.2...   

                                    pythia_1b_143000  
0  [[27.787200205189446, 0.8182145371427766, 7.11...  
1  [[14.266735727703946, -1.463596187328678, -6.4...  
2  [[11.46649704653258, -13.782047365772575, 18.4...  
3  [[-4.712632794295758, 4.099374021409617, 20.10...  
4  [[13.50587482556316, -2.5998046535715846, 11.5...

In [13]:
df.tail()

title  \
47                                 John Lester   
48           Sometimes ( Britney Spears song )   
49  Silba @-@ class landing ship @-@ minelayer   
50                            Bringing Up Baby   
51                            Brunette Coleman   

                                                 text  \
47  John Ashby Lester ( August 1 , 1871 – Septembe...   
48  " Sometimes " is a song recorded by American s...   
49  The Silba class ( sometimes the Cetina class )...   
50  Bringing Up Baby is a 1938 American screwball ...   
51  Brunette Coleman was a pseudonym used by the p...   

                                     pythia_1b_107000  \
47  [[6.839624312521729, -5.207590168499901, -18.4...   
48  [[13.344157991967714, 8.972299831254318, -13.1...   
49  [[4.967595107988772, 20.69971781108438, 4.2456...   
50  [[15.515219727209843, 23.69368284592073, -6.49...   
51  [[22.873631281212017, -3.574377877807353, 23.5...   

                                     pythia_1b_125000  \
47  [[9.927670981126711, -7.849874195246553, -14.8...   
48  [[7.557132798683836, 8.779462915562968, -8.721...   
49  [[9.76381252844729, 21.08673194761629, 2.80448...   
50  [[9.298507356273117, 24.000586082938053, 2.251...   
51  [[20.437831612151918, -5.141610368496138, 26.3...   

                                     pythia_1b_143000  
47  [[8.60120438011457, -6.809141592660386, -13.83...  
48  [[10.498247490608776, 9.87277892719864, -5.169...  
49  [[10.045533809010651, 18.122897136485832, 6.74...  
50  [[10.768181668625244, 20.573725028266335, 1.30...  
51  [[17.223898729334024, -2.607484766028246, 23.9...

In [14]:

values = df[['pythia_1b_107000', 'pythia_1b_125000', 'pythia_1b_143000']]
# Flatten each vector and concatenate them into a single numpy array
all_vectors = np.concatenate([v.flatten() for col in values.columns for v in values[col]])

# Reshape the array to have a shape of (52*3, 2048)
all_vectors = all_vectors.reshape(-1, 2048)

all_vectors # has first all the rows then columns



array([[ 27.84090873,  -3.04745889,   6.06031577, ...,   1.68131546,
         22.21159637,  29.08611985],
       [ 10.19302476,   0.05765611,  -3.43290114, ..., -18.96817882,
        -15.50027041,  15.54224204],
       [  8.47934011, -15.9882419 ,  23.33294607, ...,  -8.84259559,
        -12.43096137,   5.68953593],
       ...,
       [ 10.04553381,  18.12289714,   6.74408505, ..., -20.11232805,
         18.51703702,   6.40134145],
       [ 10.76818167,  20.57372503,   1.30942587, ..., -12.24404413,
         -8.71818904,  19.93269028],
       [ 17.22389873,  -2.60748477,  23.94018628, ...,  -8.29830259,
         -7.344635  ,   5.22939421]])

In [15]:
# Perform PCA to 3 dim
pca = PCA(n_components=2)
pca.fit(all_vectors)
pca_vectors = pca.transform(all_vectors)
pca_vectors



array([[ 4.52818427e+02,  3.33472662e+02],
       [-6.26472368e+01,  9.77348876e+01],
       [ 7.12711330e+01,  9.09936899e+00],
       [-4.19212160e+02,  2.14624629e+02],
       [-6.83005646e+01,  1.79171851e+00],
       [ 6.97702957e+02,  9.08254271e+01],
       [-2.47111663e+02,  2.17478981e+02],
       [-2.57699587e+02,  1.52143452e+02],
       [-3.79977624e+01,  1.09089556e+02],
       [ 4.58292324e+02,  1.01780361e+02],
       [ 2.08584124e+02,  8.24616821e+01],
       [-1.90340681e+02, -2.65735014e+02],
       [ 8.83138952e+01,  1.84075679e+01],
       [ 4.59391652e+02,  3.21137271e+01],
       [ 1.15548456e+03, -1.30512331e+02],
       [-4.86600141e+01,  6.02785757e+01],
       [-2.68795657e+02,  3.60919713e+01],
       [ 7.75447287e+02, -3.26149282e+02],
       [ 1.97829880e+02,  2.24903600e+02],
       [-2.04378488e+02,  2.33991317e+02],
       [ 2.13047031e+02,  2.23777065e+02],
       [-3.08127062e+02,  9.83852770e+01],
       [-2.65222468e+02,  1.67054946e+02],
       [ 1.

In [16]:
allv2 = all_vectors.reshape(3, 52, 2048)
allv2

array([[[ 4.52818427e+02,  3.33472662e+02],
        [-6.26472368e+01,  9.77348876e+01],
        [ 7.12711330e+01,  9.09936899e+00],
        [-4.19212160e+02,  2.14624629e+02],
        [-6.83005646e+01,  1.79171851e+00],
        [ 6.97702957e+02,  9.08254271e+01],
        [-2.47111663e+02,  2.17478981e+02],
        [-2.57699587e+02,  1.52143452e+02],
        [-3.79977624e+01,  1.09089556e+02],
        [ 4.58292324e+02,  1.01780361e+02],
        [ 2.08584124e+02,  8.24616821e+01],
        [-1.90340681e+02, -2.65735014e+02],
        [ 8.83138952e+01,  1.84075679e+01],
        [ 4.59391652e+02,  3.21137271e+01],
        [ 1.15548456e+03, -1.30512331e+02],
        [-4.86600141e+01,  6.02785757e+01],
        [-2.68795657e+02,  3.60919713e+01],
        [ 7.75447287e+02, -3.26149282e+02],
        [ 1.97829880e+02,  2.24903600e+02],
        [-2.04378488e+02,  2.33991317e+02],
        [ 2.13047031e+02,  2.23777065e+02],
        [-3.08127062e+02,  9.83852770e+01],
        [-2.65222468e+02,  1.670

In [32]:
import numpy as np
import gzip

# Function to compress data and return the size
def compress_and_get_size(data):
    # Convert the numpy array to a byte array
    byte_data = data.tobytes()
    # Use gzip to compress the byte array
    compressed_data = gzip.compress(byte_data)
    # Return the size of the compressed data
    return len(compressed_data)

# Iterate over the PCA vectors
for i in range(allv2.shape[0]):
    for j in range(allv2.shape[1]):
        # Get the vector
        vector = allv2[i, j, :]
        # Calculate the compressed size
        size_vector = compress_and_get_size(vector)
        # Print the size
        print(f"Compressed size of vector at checkpoint {i}, data point {j}: {size_vector} bytes")